name: Release

on:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: grafana/plugin-actions/build-plugin@build-plugin/v1.2.0
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          root_urls: https://grafana.oyabun.se
          # If using a legacy API key instead of an access policy token:
          # grafana_token: ${{ secrets.GRAFANA_API_KEY }}
